### ISSUE TITLE
希望增加一些事件支持

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee-kernel-flv#10]
比如，当fetch判断超过一段时间间隔没有拿到新数据的时候，能够抛出一些事件，这样在播放器外部可以有依据能判断是否需要超时重试。目前只通过监听video的waiting事件以及paused状态无法判断是否为直播推流连接断了的情况（当断了的时候，waiting事件触发，但是video的paused为false…）

**Comment by songguangyu** [comment]
可以新增 多久没有数据更新  就抛出error 事件，仅直播有效， 增加一个可配置默认值，设置超时时间。

**Comment by songguangyu** [comment]
@skyline0705 done。
现在新增了 心跳功能 https://github.com/Chimeejs/chimee-kernel/blob/master/readme.md
每秒触发一次，目前会回调 speed total等参数。后续会补充更多的功能。
目前你可以根据心跳的speed 来判断流是否断掉。 
同样 流异常 会触发error事件，事件详情同见文档
