### ISSUE TITLE
在播放直播流  flv 时，会出现音画不同步的问题

### ISSUE THREAD

**Issue by alert-0822** [Chimeejs/chimee-kernel-flv#12]
hi ，chimee-kernel 团队：
 在用到该插件时，我发现一个音画不同步的问题，我的配置如下： 
 new kernelFlv(document.getElementById('video'), {
          src: '直播流.flv',
          box: 'flv',
          isLive: true,
          webWorker: false,
          seekType: 'range',
          stashSize: 1024 * 64
        });
该如何解决这个问题呢，

**Comment by songguangyu** [comment]
可以提供个流看看，还有服务端转码 音视频时间戳是否对齐？

**Comment by alert-0822** [comment]
@songguangyu  这是我找到的流 ‘http://pull.stager.jp.8686c.com/stager/642746.flv’  在基本播出5s 后，会出现类似标题（音画不同步）的问题，麻烦了

**Comment by songguangyu** [comment]
我看这个流质量很低 很卡
