### ISSUE TITLE
flv 直播模式下，设置了autoplay: false但依然会自动播放

### ISSUE THREAD

**Issue by huzunjie** [Chimeejs/chimee-kernel-flv#2]
正常预期下 autoplay: false 不应该自动播放，为true才自动播放。

 参见源码：

https://github.com/Chimeejs/chimee-kernel-flv/blob/4064e11302f6189a561dd35e262c89fa9c48f1f8/lib/index.mjs#L5197

看起来是特意自动播放的，但这样导致用户配置无效、出现与预期不符的BUG。

**Comment by songguangyu** [comment]
kernel 层加一个判断
