### ISSUE TITLE
还要点脸不，B站的东西直接搬过来 连注释都没有改

### ISSUE THREAD

**Issue by yu305306** [Chimeejs/chimee-kernel-flv#4]
还以为你们研究新的一套flv 的解码。还是把B站的搬过来。

**Comment by songguangyu** [comment]
兄弟 代码都是开源的 代码里也MIT协议，这样无脑喷不太好吧？

**Comment by songguangyu** [comment]
我们做的是播放器解决方案，flv的编解码部分使用了 flv.js的 MIT协议的开源代码，代码中也明确标明了，这样可以理解了吗？是否理智对待。

**Comment by yu305306** [comment]
兄弟，你们用了，就要尊重别人 ，最起码 你在git下面要注释好。 而不是在代码里面用了，还把部分的搬过来，开源虽然是好。但是提都不提出来。不可以。别人是一个大的东西

**Comment by songguangyu** [comment]
兄弟 你可以先看一下MIT协议 然后再来喷好吗？ 我们用他的部分代码 是因为 他的功能不满足我们的需求和后续的规划 所以引入了部分代码。MIT协议 有说要在git下面注释吗？ 可不可是你定的？

**Comment by xqq** [comment]
flv.js 整个项目都是 Apache License 2.0

**Comment by songguangyu** [comment]
@xqq  https://github.com/Chimeejs/chimee-flv2fmp4 项目里使用 flv.js 都在文件前有声明。

**Comment by songguangyu** [comment]
@yu305306 已经和 flv.js 作者 进行了沟通，之前沟通不畅锁导致的问题已经消除误会。
https://github.com/Chimeejs/chimee-flv2fmp4 项目遵循 apache2 项目。
并且对 flv.js 项目和作者表示感谢。
