### ISSUE TITLE
flv 容器模式下，销毁播放器会出现异常

### ISSUE THREAD

**Issue by huzunjie** [Chimeejs/chimee-kernel-flv#5]
![image](https://user-images.githubusercontent.com/3885060/32759427-00750736-c8af-11e7-9bdd-7866e8d7265f.png)

如图，相关版本：
    "chimee": "^0.5.0"
    "chimee-kernel-flv": "^1.3.1"

**Comment by songguangyu** [comment]
fix it in 1.3.2, thank you.
