### ISSUE TITLE
在使用原生清晰度切换的时候出错

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee-kernel-flv#8]
![image](https://user-images.githubusercontent.com/1788280/32886839-f5f2895a-cafc-11e7-9ff2-3c5ecb413cda.png)
![image](https://user-images.githubusercontent.com/1788280/32886842-f8fdabca-cafc-11e7-8187-99c83b7ab864.png)

**Comment by songguangyu** [comment]
清晰度切换之前支持点播
直播情况下，hls上有切换清晰度的方法，flv这个需要在调研一下，能否无缝切流，或者提供切流方法。
明天计划一下 给出具体方案

**Comment by toxic-johann** [comment]
嗯嗯。

需要提供一下几点

* hls 的切换方法
* flv 的切换方法

目的：

希望 silentLoad 一个接口可以解决掉这几个同类不同类的问题。

**Comment by toxic-johann** [comment]
直播的清晰度切换现已不需要 seek。故此 issue 关闭。
